### ISSUE TITLE
module rugby

### ISSUE THREAD

**Issue by Manu85340** [KristjanESPERANTO/MMM-OneCallWeather#10]
@KristjanESPERANTO Hello, I am looking for a module to follow the scores and rankings of rugby in France the "top 14" and the 6 nations tournament. Do you know if there is a module for MM? I searched but I can't find anything, and if it is possible to modify a soccer module for example to "transform" it with rugby data, I am a beginner, you have already helped me and I thank you

**Comment by KristjanESPERANTO** [comment]
Unfortunately, I don't know such a module and can't find one in [the module list](https://github.com/MagicMirrorOrg/MagicMirror/wiki/3rd-party-modules). You've already asked [this question in the forum](https://forum.magicmirror.builders/topic/18313/hello-everyone-do-you-know-if-there-is-an-mm-module-for-rugby), so if no one has responded, there probably isn't one yet.

**Comment by Manu85340** [comment]
thank you for your answer, I actually asked the question on the forum but as I didn't get an answer, I said to myself that I would ask you in case you had a "tip"
