### ISSUE TITLE
Feels like

### ISSUE THREAD

**Issue by 85340olonne** [KristjanESPERANTO/MMM-OneCallWeather#12]
Kristjan hello, do you think it is possible to change the “feels like” line in French, thank you for your help

**Comment by KristjanESPERANTO** [comment]
Sorry, I just noticed your question. Thanks for bringing this up!

I just added an translation. Please update your module and check it out :smiley:

**Comment by 85340olonne** [comment]
thank you very much, I just updated it, it’s greatEnvoyé depuis l'application Mail Orange----------------De: "Kristjan ESPERANTO" ***@***.***>Envoyé: samedi, 16 mars 2024, 15:47À: "KristjanESPERANTO/MMM-OneCallWeather" ***@***.***>Cc: "85340olonne" ***@***.***>;"Author" ***@***.***>Objet: Re: [KristjanESPERANTO/MMM-OneCallWeather] Feels like (Issue #12)   
Sorry, I just noticed your question. Thanks for bringing this up!
I just added an translation. Please update your module and check it out 😃

**Comment by KristjanESPERANTO** [comment]
You are welcome! I'm happy that the module is being used. If you haven't already done so, please give the module a star :-)
