### ISSUE TITLE
color temperature settings problem

### ISSUE THREAD

**Issue by Manu85340** [KristjanESPERANTO/MMM-OneCallWeather#8]
@KristjanESPERANTO hello I installed your MMM-OneCallWeather module thanks to
@sdetweil, he helped me with this module and many other things and I have a question in the readme he wrote there:
"colored If set 'colored' to true the min-temp get a blue tone and the max-temp get a red tone.

Default value: true"
I added this to my js.config but the values remain white am I doing something wrong?
you asked me to put my js.config here it is:
```
{
			disabled: false,
    			module: "MMM-OneCallWeather",
    			position: "top_right", // This can be any of the regions.
    			// Best results in bottom_bar region due to horizontal default layout and icon sizes.
    			config: {
      			// See 'Configuration options' for more information.
			windunits: "kmh",
			updateInterval: 20 * 60 * 1000, // every 20 minutes

			tempUnits: "C",
			units: "metric",
			colored: "true",
			layout: "default",
      			latitude: "46.561180", // Longitude from https://www.latlong.net/
      			longitude: "-1.782440", // Longitude from https://www.latlong.net/ - is West + is East of London
      			apikey: "xxxxxxxxxxxxxxxxxxxxxxxxxxx" // openweathermap.org API key 
			
    			}
  		},

```

**Comment by KristjanESPERANTO** [comment]
Okay, that's very interesting. I took a closer look at the code. The colored option was not fully implemented. I have fixed that now :rocket: Please update the module and try again :slightly_smiling_face:

To update the module:

```sh
cd ~/MagicMirror/modules/MMM-OneCallWeather
git pull
```

**Comment by KristjanESPERANTO** [comment]
And you must set the value for colored without the quotation mark. Like this:

```js
colored: true,
```

**Comment by Manu85340** [comment]
@KristjanESPERANTO perfect, thank you for your answer, it works

**Comment by KristjanESPERANTO** [comment]
You are welcome 🙂

**Comment by Manu85340** [comment]
@KristjanESPERANTO hello, do you know how I can enlarge the size of the "bubble" or there is the wind speed, thank you for your help



![1706648324980-cc5eaf4e-5689-4b3d-9046-0a20229972bc-image](https://github.com/KristjanESPERANTO/MMM-OneCallWeather/assets/28225963/90be58a1-6925-4c6b-8cf7-fe076832eb81)
